programming_questions = {
    "What is the keyword used to define a function in Python?": "def",
    "In which language are web pages styled?": "CSS",
    "Which symbol is used to denote comments in Python?": "#",
    "What is the name of the method used to initialize objects in Python?": "__init__",
    "What does HTML stand for?": "HyperText Markup Language",
    "Which keyword is used to create a variable in JavaScript?": "var",
    "What is the file extension for Python files?": ".py",
    "Which method is used to add an element to the end of a list in Python?": "append()",
    "What does SQL stand for?": "Structured Query Language",
    "What symbol is used to access attributes of an object in Python?": ".",
    "What is the output of print(2 + 3 * 2) in Python?": "8",
    "Which loop in Python is used to iterate over a sequence?": "for",
    "What is the main function called in C and C++?": "main()",
    "What does CSS stand for?": "Cascading Style Sheets",
    "Which data type is used to store text in Python?": "str",
    "What is the output of print(len(\"Hello\")) in Python?": "5",
    "Which Python keyword is used to handle exceptions?": "try",
    "What is a Boolean value in programming?": "True or False",
    "Which operator is used for logical AND in Python?": "and",
    "What is the default port number for HTTP?": "80"
}

science_questions = {
    "What planet is known as the Red Planet?": "Mars",
    "What is the chemical symbol for water?": "H2O",
    "What force keeps us on the ground?": "Gravity",
    "What is the process by which plants make their food?": "Photosynthesis",
    "What gas do plants absorb from the atmosphere?": "Carbon dioxide",
    "Who is known as the father of modern physics?": "Albert Einstein",
    "What is the powerhouse of the cell?": "Mitochondria",
    "What is the chemical symbol for gold?": "Au",
    "Which planet is closest to the Sun?": "Mercury",
    "What is the largest organ in the human body?": "Skin",
    "What is the basic unit of life?": "Cell",
    "What part of the cell contains genetic material?": "Nucleus",
    "What is the common name for the compound NaCl?": "Table salt",
    "What is the hardest natural substance on Earth?": "Diamond",
    "What is the study of living organisms called?": "Biology",
    "What planet is known for its rings?": "Saturn",
    "Which element is essential for the production of thyroid hormones?": "Iodine",
    "What is the primary gas found in the Earth’s atmosphere?": "Nitrogen",
    "What is the chemical formula for carbon dioxide?": "CO2",
    "Which organ in the human body is responsible for pumping blood?": "Heart"
}

math_questions = {
    "What is 5 + 3?": 8,
    "What is the square root of 16?": 4,
    "What is 12 ÷ 4?": 3,
    "What is the value of π (pi) up to two decimal places?": 3.14,
    "What is 10% of 100?": 10,
    "What is 7 * 8?": 56,
    "What is 25 - 9?": 16,
    "What is the sum of angles in a triangle?": 180,
    "What is 9 * 9?": 81,
    "What is 6 squared (6²)?": 36,
    "What is 20 ÷ 5?": 4,
    "What is the perimeter of a square with side length 5?": 20,
    "What is 15% of 200?": 30,
    "What is 2³ (2 raised to the power of 3)?": 8,
    "What is the value of 3! (3 factorial)?": 6,
    "What is the greatest common divisor (GCD) of 8 and 12?": 4,
    "What is the smallest prime number?": 2,
    "What is 1000 - 250?": 750,
    "What is the next number in the sequence: 2, 4, 6, 8, ...?": 10,
    "What is the area of a rectangle with length 7 and width 3?": 21
}